# Generated by Django 2.0.4 on 2018-05-01 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_text', models.CharField(max_length=50)),
                ('target_text', models.CharField(blank=True, max_length=150)),
                ('nmt_text', models.CharField(max_length=250)),
            ],
        ),
    ]
